version: "3"

services:
  database:
    container_name: database_name
    image: postgres:alpine3.18
    ports:
      - 5432:5432
    volumes:
      - volume_name:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=user_password

  pgAdmin:
    depends_on:
      - database
    container_name: pgAdmin
    image: dpage/pgadmin4:7.3
    ports:
      - 8083:80
    volumes:
      - ./pgAdmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=H0L4_D5M
      - PGADMIN_DEFAULT_EMAIL=candidatoabaja@google.com

volumes:
  volume_name:
    external: true